### ISSUE TITLE
Exact source

### ISSUE THREAD

**Issue by eliflab** [eliflab/European-Parliament-Open-Data#4]
From @marado:

> I have a project on github that provides a list of MEPs on twitter by country, both on CSV and JSON formats:
https://github.com/marado/MEPsOnTwitter

> I  recently moved the source for this info to https://docs.google.com/spreadsheets/d/14Y3MBdIVsKt361l8qMGEecjGkxV5PCOfuKOMptfBB-k/ but then I bumped into this repository, and it seems that either this is the source for that spreadsheet or the other way around.

> As  I want to be using the most complete and up-to-date source, can you please tell me (if you can) which of these sources is the "primary" one?

> Thanks

Hi @marado ... I created myself that spreadsheet few months ago, but then I decided to keep data up to date only on github, so to make data and changes traceable and easier to find.
That spreadsheet is then an old version of this project. The *csv list you find in this repository is the only one we are currently trying to keep up to date.

**Comment by marado** [comment]
Thanks for your reply.
Since your CSV does exactly what I need, I'll point to it and just distribute the js on mine.
Would you be interested in having the JS version of the list on your repository (I can summit the relevant script and result), or do you prefer to keep this repository as the CSV only?

Keep up the good work!

**Comment by eliflab** [comment]
We prefer to keep only the CSV here, but of course you are free to generate the json and we can link it in the readme if it's ok to you :)

**Comment by marado** [comment]
Done :-)
I still intend to add more info on the generated js itself (source,
version, license), but it's already on my project's README.
Thanks!

PS - this issue can now be closed
